# Example GitHub Actions workflow for Claude Code with full development environment setup
#
# To use this workflow:
# 1. Copy this file to .github/workflows/claude.yml
# 2. Replace the existing claude.yml with this version
# 3. Ensure CLAUDE_CODE_OAUTH_TOKEN secret is set
# 4. Optionally: Add CONVEX_URL secret if you have an existing Convex deployment
#
# This workflow adds pnpm, Node.js setup, and dependency installation before running Claude Code,
# enabling Claude to run dev servers and test the application.

name: Claude Code (with full setup)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # ============================================
      # NEW: Setup development environment
      # ============================================

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install expect (for noninteractive Convex)
        run: sudo apt-get update && sudo apt-get install -y expect

      # Optionally: Set up Convex URL if you have one
      # Uncomment and add CONVEX_URL to repository secrets
      # - name: Setup Convex URL
      #   run: echo "VITE_CONVEX_URL=${{ secrets.CONVEX_URL }}" >> $GITHUB_ENV

      # ============================================
      # Run Claude Code
      # ============================================

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read

          # Optional: Give a custom prompt to Claude. If this is not specified, Claude will perform the instructions specified in the comment that tagged it.
          # prompt: 'Update the pull request description to include a summary of changes.'

          # Optional: Add claude_args to customize behavior and configuration
          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/sdk#command-line for available options
          # claude_args: '--model claude-opus-4-1-20250805 --allowed-tools Bash(gh pr:*)'

